apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-unitest-task

spec:
  description: this will be the task to run unittest for python
  params:
    - default: ""
      description: The root directory of the repository that Ozone pulls code from
      name: PROJECT_DIR

    - default: ""
      description: The username for authentication to the repository to pull code from
      name: REPO_USER

    - default: ""
      description: The password for authentication to the repository to pull code from
      name: REPO_PASSWORD

    - default: ""
      description: A diallable URL to connect to the repository through Ozone
      name: REPO_URL

    - default: ""
      description: The branch to pull the code from for an image build
      name: REPO_BRANCH

  steps:
    - image: "gcr.io/ozoneprod/alpine/git:latest"
      name: git-clone
      script: |
        echo "anc"
        set +x
        rm -rf $(workspaces.gitpull.path)/$(params.PROJECT_DIR)
        echo $(params.REPO_BRANCH) --recursive https://"$(params.REPO_USER)":"$(params.REPO_PASSWORD)"@"$(params.REPO_URL)" $(workspaces.gitpull.path)/$(params.PROJECT_DIR)
        git clone -b $(params.REPO_BRANCH) --recursive https://"$(params.REPO_USER)":"$(params.REPO_PASSWORD)"@"$(params.REPO_URL)" $(workspaces.gitpull.path)/$(params.PROJECT_DIR)
        ls
        cd /gitpull/$(params.PROJECT_DIR)
        ls
        cat README.md

    - image: "gcr.io/ozoneprod/python:latest"
      name: ozone-python-test
      script: |
        set +x
        cd $(workspaces.gitpull.path)/$(params.PROJECT_DIR)
        ls
        python --version
        python -m compileall ./
        pip3 install -U pip
        pip3 install -r requirements.txt
        pip3 install coverage
        pip3 install pytest
        # python3 -m unittest discover -p "*_test.py"
        python3 -m coverage run -m pytest
        python3 -m coverage report -m
        python3 -m coverage html
        ls
        cd htmlcov
        ls

  workspaces:
    - description: Where git pulls
      mountPath: /gitpull
      name: gitpull
